/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { ProductPage } from '../../product/models/product.page.model';

export interface OrderItem {
    id?: number;
    price?: number;
    quantity?: number;
    product?: ProductPage;
    order?: Order;
}

