/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from '../../user/models/user.model';
import {OrderItem} from './order-item';



export interface Order {
    orderId?: number;
    quantity?: number;
    totalAmount?: number;
    orderItems?: Set<OrderItem>;
    user?: User;
}

